CREATE OR REPLACE TRIGGER INSERT_ROW_NUMBER_TRIGGER BEFORE INSERT ON USERINFO FOR EACH ROW
BEGIN
    IF ( :new.ROW_NUMBER IS NULL ) THEN
        SELECT REPORT_ROW_NUMBER_SEQUENCE.nextval INTO :new.ROW_NUMBER FROM dual;
    END IF;
END;   