CREATE TABLE USERINFO 
(
  GB_HP NUMBER 
, PERCENTAGE_HP NUMBER 
, PRICE_PER_GB_GP NUMBER 
, GB_MP NUMBER 
, PERCENTAGE_MP NUMBER 
, PRICE_PER_GB_MP NUMBER 
, GB_ROP NUMBER 
, PERCENTAGE_ROP NUMBER 
, PRICE_PER_GB_ROP NUMBER 
, FACTOR NUMBER 
, CREATION_DATE TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL 
, CONTACT_INFO_ID VARCHAR2(20 BYTE) NOT NULL 
, ROW_NUMBER NUMBER 
, CONSTRAINT USERINFO_PK PRIMARY KEY 
  (
    CONTACT_INFO_ID 
  , CREATION_DATE 
  )
  ENABLE 
);

ALTER TABLE USERINFO
ADD CONSTRAINT USERINFO_CONTACTINFO_FK1 FOREIGN KEY
(
  CONTACT_INFO_ID 
)
REFERENCES CONTACTINFO
(
  ID 
)
ENABLE;
