CREATE TABLE COMPANYINFO 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, PHONE VARCHAR2(20 BYTE) NOT NULL 
, ADDRESS1 VARCHAR2(100 CHAR) NOT NULL 
, ADDRESS2 VARCHAR2(100 CHAR) 
, ZIPCODE VARCHAR2(20 BYTE) NOT NULL 
, CITY VARCHAR2(20 BYTE) NOT NULL 
, COUNTRY VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT COMPANYINFO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);
