CREATE TABLE CONTACTINFO 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, NAME VARCHAR2(20 CHAR) NOT NULL 
, FIRST_NAME VARCHAR2(20 BYTE) NOT NULL 
, CODE VARCHAR2(20 BYTE) NOT NULL 
, EMAIL VARCHAR2(40 CHAR) NOT NULL 
, ADDRESS1 VARCHAR2(100 CHAR) NOT NULL 
, PHONE VARCHAR2(40 BYTE) NOT NULL 
, ZIPCODE VARCHAR2(20 BYTE) NOT NULL 
, CITY VARCHAR2(20 BYTE) NOT NULL 
, COUNTRY VARCHAR2(20 BYTE) NOT NULL 
, COMPANY_ID VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT CONTACTOINFO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE CONTACTINFO
ADD CONSTRAINT CONTACTINFO_UK1 UNIQUE 
(
  CODE 
)
ENABLE;

ALTER TABLE CONTACTINFO
ADD CONSTRAINT CONTACTINFO_COMPANYINFO_FK1 FOREIGN KEY
(
  COMPANY_ID 
)
REFERENCES COMPANYINFO
(
  ID 
)
ENABLE;
