CREATE TABLE USERINFO 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, GB_HP NUMBER 
, PERCENTAGE_HP NUMBER 
, PRICE_PER_GB_GP NUMBER 
, GB_MP NUMBER 
, PERCENTAGE_MP NUMBER 
, PRICE_PER_GB_MP NUMBER 
, GB_ROP NUMBER 
, PERCENTAGE_ROP NUMBER 
, PRICE_PER_GB_ROP NUMBER 
, FACTOR NUMBER 
, CREATION_DATE TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP 
, CONTACT_INFO_ID VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT USERINFO_PK PRIMARY KEY 
  (
    ID 
  , CONTACT_INFO_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE USERINFO
ADD CONSTRAINT USERINFO_CONTACTINFO_FK1 FOREIGN KEY
(
  CONTACT_INFO_ID 
)
REFERENCES CONTACTINFO
(
  ID 
)
ENABLE;
